{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sendplane.secretName" . }}
  labels:
    {{- include "sendplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  SENDPLANE_STORE_DSN: {{ .Values.secrets.storeDSN | quote }}
  SENDPLANE_SECRETS_KEY: {{ .Values.secrets.secretsKey | quote }}
  SENDPLANE_WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  {{- with .Values.secrets.probeHMACKey }}
  SENDPLANE_PROBE_HMAC_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.probeWebhookSecret }}
  SENDPLANE_PROBE_WEBHOOK_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
