apiVersion: v1
kind: Service
metadata:
  name: {{ include "sendplane.fullname" . }}-control
  labels:
    {{- include "sendplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: control
spec:
  type: ClusterIP
  selector:
    {{- include "sendplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control
  ports:
    - name: http
      port: {{ .Values.control.service.port }}
      targetPort: http
